matrix:
- name: Markdown
  aspell:
    d: en_US
    ignore-case: true
    lang: en
  default_encoding: utf-8
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/.wordlist-in-english.txt
    - .github/.wordlist-persons.txt
    - .github/.wordlist-places.txt
    - .github/.wordlist-technical.txt
  hunspell:
    d: en_US
    ignore-case: true
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources: ['_i18n/en/**/*.md']
