name: Spelling action
on:
  pull_request:
    types: [opened, synchronize]
    paths: ['_i18n/**']
  push:
    paths: ['_i18n/**', '.github/*wordlist*.txt']
  workflow_dispatch:

jobs:
  spelling_in_english:
    name: Spelling in English
    uses: ./.github/workflows/spelling_checker.yml
    with:
      config: '.github/.spellcheck-in-english.yml'
      spellchecker: aspell

  spelling_in_polish:
    name: Spelling in Polish
    uses: ./.github/workflows/spelling_checker.yml
    with:
      config: '.github/.spellcheck-in-polish.yml'
      spellchecker: aspell
