name: Spelling action
on:
  pull_request:
    types: [opened, synchronize]
    paths: ['_i18n/**']
  push:
    paths: ['_i18n/**']
  workflow_dispatch:
    inputs:
      spellchecker:
        default: aspell
        options: ['aspell']
        required: true
        type: choice

jobs:
  spelling:
    env:
      SPELLCHECKER_FALLBACK: aspell
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
      - name: Install aspell
        run: sudo apt-get install aspell aspell-en aspell-pl
      - name: Spell check in English
        run: python -m pyspelling -c ${{ env.CONFIG }} -s ${{ env.SPELLCHECKER }}
        env:
          CONFIG: '.github/.spellcheck-in-english.yml'
          SPELLCHECKER: ${{ github.event.inputs.spellchecker || env.SPELLCHECKER_FALLBACK }}
      - name: Spell check in Polish
        run: python -m pyspelling -c ${{ env.CONFIG }} -s ${{ env.SPELLCHECKER }}
        env:
          CONFIG: '.github/.spellcheck-in-polish.yml'
          SPELLCHECKER: ${{ github.event.inputs.spellchecker || env.SPELLCHECKER_FALLBACK }}
